import { Markup } from 'telegraf';
import { DELETE_EXERCISE_BUTTON, DELETE_EXERCISE_CALLBACK, EXERCISE_GUIDE_BUTTON, EXERCISE_GUIDE_CALLBACK, GET_EXERCISE_DAY_BUTTON, GET_EXERCISE_DAY_CALLBACK, GET_EXERCISE_WEEK_BUTTON, GET_EXERCISE_WEEK_CALLBACK, POST_EXERCISE_BUTTON, POST_EXERCISE_CALLBACK, SEMANAL_SPLIT_BUTTON, SEMANAL_SPLIT_CALLBACK, UPDATE_EXERCISE_BUTTON, UPDATE_EXERCISE_CALLBACK } from '../mainMenu/buttons';

export const inlineKeyboardMenu= Markup.inlineKeyboard([
  [
    Markup.button.callback(`📝 ${POST_EXERCISE_BUTTON}`, POST_EXERCISE_CALLBACK),
    Markup.button.callback(`🔄 ${UPDATE_EXERCISE_BUTTON}`, UPDATE_EXERCISE_CALLBACK)
  ],
  [
    Markup.button.callback(`📅 ${GET_EXERCISE_DAY_BUTTON}`, GET_EXERCISE_DAY_CALLBACK),
    Markup.button.callback(`📆 ${GET_EXERCISE_WEEK_BUTTON}`, GET_EXERCISE_WEEK_CALLBACK)
  ],
  [Markup.button.callback(`🗑️ ${DELETE_EXERCISE_BUTTON}`, DELETE_EXERCISE_CALLBACK)],
  [
    Markup.button.callback(`📘 ${EXERCISE_GUIDE_BUTTON}`, EXERCISE_GUIDE_CALLBACK),
    Markup.button.callback(`📊 ${SEMANAL_SPLIT_BUTTON}`, SEMANAL_SPLIT_CALLBACK)
  ],
])
